name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install LilyPond
      run: |
        wget --no-verbose https://lilypond.org/download/binaries/linux-64/lilypond-2.22.2-1.linux-64.sh
        sudo sh lilypond-2.22.2-1.linux-64.sh --batch

    - name: Run tests
      run: lilypond test-suite/bend-test.ly

    - name: Archive
      uses: actions/upload-artifact@main
      with:
        name: ${{ runner.os }} artifacts
        path: bend-test.pdf
        if-no-files-found: error
